#- name: copy logstash config
#  template:
#    src: logstash.conf
#    dest: /etc/logstash/conf.d/logstash.conf
#- name: restart logstash
#  systemd:
#    name: logstash
#    state: restarted
#    enabled: yes

- name: COpy Logstash Config
  template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: Restart logstash
  systemd:
    name: logstash
    state: restarted
    enabled: yes