filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/{{COMPONENT}}.log   # telling where these logs are should go
# here fields are the one which are used as keys to find the logs
    fields:
      componentName: {{COMPONENT}}
      env: {{ENV}}
      logType: json
      appLang: nodejs
    json.keys_under_root: true

output.logstash:
  hosts: ["172.31.62.82:5044"]

## Defaults
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 1

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

