- name: update prometheus configuration
  template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: update record files
  template:
    src: records.yml
    dest: /opt/prometheus/records.yml


- name: restart prometheus services
    systemd:
      name: prometheus
      state: restart
      enable: yes
