- name: filebeat repo
  copy:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo
- name: install filebeat
  yum:
    name: filebeat
    state: installed

- name: copy configuration
  template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml