groups:
  - name: Instance alerts
    rules:
      - alert: InstanceDown
        exrp: up == 0
        for: 1m
        labals:
          severity: critical
        annotations:
          summery: "instance Down - [{{ $labels.instance}}]"
          description: {%raw%}"instance Down - [{{ $labels.instance}}]"{%endraw%}

  - name: CPU alerts
    rules:
     - alert: CPUusagealert
        expr: CpuUsagePercentage > 80
        for: 1m
        labels:
          severity: critical
          type: InstanceAlert
          kind: CpuHighUsage
        annotations:
          summery: {%raw%}"CPU usage is high- [{{ $labels.instance}}]"{%endraw%}
          description: {%raw%}"CPU usage is high- [{{ $labels.instance}}]"{%endraw%}
  - name: Memory alerts
    rules:
      - alert: MemoryUsageAlert
        expr: memoryusagepercentage > 89
        for: 1m
        labels:
          severity: critical
          type: Memoryfullalert
          kind: MemoryUsageHigh
        annotations:
          summery: {%raw%}"Memory usage is high- [{{ $labels.instance}}]"{%endraw%}
          description: {%raw%}"Memory usage is high- [{{ $labels.instance}}]"{%endraw%}