groups:

{% for comp in COMPONENTS %}
- name: node-{{comp}}  Alerts
    rules:
      - alert: "{{comp}}-Application-Down"
        expr: node_systemd_unit_state{instance={{comp}},name="basic.target", state="active"} == 0
        for: 1m
        labels:
          severity: critical
          type: instanceAlert
          kind: serviceAlert
        annotations:
          summary: "{{comp}} Component Service Down - IP - {%raw%}[{{ $labels.instance}}], Name - [ {{ $labels.instanceName} ]"{%endraw%}


          description: "{{comp}} Component Service Down - IP - {%raw%}[{{ $labels.instance}}], Name - [ {{ $labels.instanceName}} ]"{%endraw%}


{% endfor %}