groups:
{% for comp in COMPONENTS %}
  - name: cart- Alerts
    rules:
      - alert: {{comp}} -InstanceDown
        expr: node_systemd_unit_state{instance={{comp}},name="basic.target", state="active"} != 0
        for: 1m
        labels:
          severity: critical
          type: instanceAlert
          kind: instanceDown
        annotations:
          summary: {%raw%}"{{comp}} Down - IP - [{{ $labels.instance}}], Name - [{{ $labels.instanceName}}]"{%endraw%}
          description: {%raw%}"{{comp}} - IP - [{{ $labels.instance}}], Name - [{{ $labels.instanceName}}]"{%endraw%}

{% endfor %}