groups:
{% for comp in COMPONENTS %}
  - name: cart- Alerts
    rules:
      - alert: {{comp}} -InstanceDown
        expr: node_systemd_unit_state{instance={{comp}},name="basic.target", state="active"} == 0
        for: 1m
        labels:
          severity: critical
          type: instanceAlert
          kind: instance-Down
        annotations:

          summary: "{{comp}}-{%raw%}"instance - IP - [{{ $labels.instance}}], Name - [{{ $labels.instanceName}}]"{%endraw%}"
          description: "{{comp}}-{%raw%}"instance - IP - [{{ $labels.instance}}], Name - [{{ $labels.instanceName}}]"{%endraw%}"

{% endfor %}