#groups:
#{% for comp in COMPONENTS %}
#  - name: cart- Alerts
#    rules:
#      - alert: {{comp}} -InstanceDown
#        expr: node_systemd_unit_state{instance={{comp}},name="basic.target", state="active"} == 0
#        for: 1m
#        labels:
#          severity: critical
#          type: instanceAlert
#          kind: serviceAlert
#        annotations:
#          summary: "{{comp}} Component Service Down - IP - {%raw%}[{{ $labels.instance}}], Name - [{{ $labels.instanceName}}]"{%endraw%}
#
#          description: "{{comp}} Component Service Down - IP - {%raw%}[{{ $labels.instance}}], Name - [{{ $labels.instanceName}}]"{%endraw%}
#
#  {% endfor %}

groups:
  {% for component in COMPONENTS %}
- name: {{component}} Application Alert
  rules:
    - alert: {{component}} Application Down
      expr: node_systemd_unit_state{instance={{component}},name="basic.target", state="active"} == 0
      for: 1m
      labels:
        severity: critical
        type: appAlert
        kind: serviceAlert
        appName: {{component|lower}}
      annotations:
        description: "{{component}} Component Service Down - IP - {%raw%}[{{ $labels.instance}}], Name - [{{ $labels.instanceName}}]"{%endraw%}
  {% endfor %}