groups:
  - name: custom
    rules:
      - record: InstanceDown
        expr: up
      - record: MemoryUsageAlert
        expr: 100 - ceil((node_memory_MemFree_bytes / node_memory_MemTotal_bytes * 100))
      - record: cpuUsagePercentage
        expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[30s])) * 100)
